#!/usr/bin/env bash
brew install autoconf
brew install automake
brew install awscli
brew install bash-completion
brew install boot2docker
brew install brew-cask
brew install cairo
brew install ccat
brew install colortail
brew install couchdb
brew install cscope
brew install czmq
brew install dnsmasq
brew install docker
brew install erlang
brew install fontconfig
brew install fontforge
brew install freetype
brew install gdbm
brew install gettext
brew install git
brew install git-flow
brew install glib
brew install go
brew install gobject-introspection
brew install harfbuzz
brew install hub
brew install icu4c
brew install jenv
brew install jpeg
brew install libevent
brew install libffi
brew install libgpg-error
brew install libksba
brew install libpng
brew install libtiff
brew install libtool
brew install libyaml
brew install macvim
brew install maven
brew install mono
brew install node
brew install nspr
brew install openssl
brew install p7zip
brew install pango
brew install pcre
brew install pixman
brew install pkg-config
brew install python
brew install rabbitmq
brew install rbenv
brew install readline
brew install rethinkdb
brew install ruby
brew install ruby-build
brew install scala
brew install serf
brew install sphinx
brew install spidermonkey
brew install sqlite
brew install subversion
brew install sudolikeaboss
brew install swig
brew install tmux
brew install tree
brew install unixodbc
brew install wget
brew install wxmac
brew install zeromq